<?php

DEFINE("DB_HOST", "localhost");
DEFINE("DB_NAME", "ShoppingCart");
DEFINE("DB_USER", "root");
DEFINE("DB_PASS", "");
DEFINE("PAPER", "jfrikl^#@&*wsa^$#&*gjr__--eiu--AAa");
DEFINE("HASH_ALGORITHM", "sha384");
DEFINE("KEYSTRECHITERATIONS", 100000);

DEFINE("USERNAME_MIN_LENGTH", 5);
DEFINE("USERNAME_MAX_LENGTH", 50);

DEFINE("PASSWORD_MIN_LENGTH", 5);
DEFINE("PASSWORD_MAX_LENGTH", 60);